import { StyleSheet } from "react-native";
import { AUTH, AUTH_PAD } from "./authUi";
import { WORKOUT_UI } from "./workoutScreenUi";

export const CATALOG_UI = {
  rowGap: 8,
  thumbSize: 52,
  cardRadius: 12,
} as const;

export const exerciseCatalogStyles = StyleSheet.create({
  toolbarCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: AUTH.cardBorder,
    backgroundColor: "rgba(10, 10, 12, 0.85)",
    padding: 12,
    gap: 10,
    marginBottom: 10,
  },
  kicker: {
    color: AUTH.gold,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.55,
    textTransform: "uppercase",
  },
  slotsPill: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: WORKOUT_UI.borderGold,
    backgroundColor: WORKOUT_UI.chipBgActive,
  },
  slotsPillMuted: {
    borderColor: AUTH.fieldBorder,
    backgroundColor: WORKOUT_UI.chipBg,
  },
  slotsPillText: {
    color: AUTH.gold,
    fontSize: 12,
    fontWeight: "600",
  },
  slotsPillTextMuted: {
    color: AUTH.muted,
  },
  searchWrap: {
    flexDirection: "row",
    alignItems: "center",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: AUTH.fieldBorder,
    backgroundColor: AUTH.fieldBg,
    paddingLeft: 10,
    paddingRight: 4,
  },
  searchIcon: {
    color: AUTH.faint,
    fontSize: 16,
    marginRight: 6,
  },
  searchInput: {
    flex: 1,
    paddingVertical: 10,
    color: AUTH.steel,
    fontSize: 15,
  },
  searchClear: {
    width: 32,
    height: 32,
    alignItems: "center",
    justifyContent: "center",
  },
  searchClearText: {
    color: AUTH.muted,
    fontSize: 22,
    lineHeight: 24,
  },
  sortRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 2,
  },
  sortLabel: {
    color: AUTH.faint,
    fontSize: 10,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.4,
    marginRight: 2,
  },
  sortChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: AUTH.fieldBorder,
    backgroundColor: WORKOUT_UI.chipBg,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  sortChipActive: {
    borderColor: WORKOUT_UI.borderGold,
    backgroundColor: WORKOUT_UI.chipBgActive,
  },
  sortChipText: {
    color: AUTH.muted,
    fontSize: 11,
    fontWeight: "600",
  },
  sortChipTextActive: {
    color: AUTH.gold,
  },
  activeFilterChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(212, 175, 55, 0.35)",
    backgroundColor: "rgba(35, 32, 22, 0.75)",
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  activeFilterChipText: {
    color: AUTH.gold,
    fontSize: 11,
    fontWeight: "600",
  },
  activeFilterChipX: {
    color: AUTH.gold,
    fontSize: 14,
    fontWeight: "700",
    lineHeight: 16,
  },
  modalHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 12,
    marginBottom: 12,
    paddingHorizontal: 2,
  },
  modalHeaderText: {
    flex: 1,
    minWidth: 0,
    gap: 4,
  },
  modalTitle: {
    color: AUTH.neutral100,
    fontSize: 20,
    fontWeight: "700",
  },
  modalSubtitle: {
    color: AUTH.muted,
    fontSize: 13,
    lineHeight: 18,
  },
  modalHeaderSlots: {
    alignSelf: "flex-start",
  },
  sectionHeader: {
    backgroundColor: AUTH.bg,
    paddingTop: 10,
    paddingBottom: 6,
    paddingHorizontal: 2,
  },
  sectionHeaderText: {
    color: AUTH.gold,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  stickyToolbar: {
    backgroundColor: AUTH.bg,
    zIndex: 2,
  },
  floatingSectionChip: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    zIndex: 3,
    backgroundColor: AUTH.bg,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(212, 175, 55, 0.22)",
    paddingTop: 6,
    paddingBottom: 8,
    paddingHorizontal: 2,
  },
  swipeStrip: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    width: 72,
    backgroundColor: "rgba(35, 32, 22, 0.98)",
    borderRightWidth: 1,
    borderRightColor: "rgba(212, 175, 55, 0.35)",
    alignItems: "center",
    justifyContent: "center",
  },
  swipeStripText: {
    color: AUTH.gold,
    fontSize: 11,
    fontWeight: "700",
  },
  rowCardHighlight: {
    borderColor: "rgba(212, 175, 55, 0.55)",
    backgroundColor: "rgba(28, 24, 14, 0.85)",
  },
  rowNameRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
  },
  inRoutineBadge: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(212, 175, 55, 0.45)",
    backgroundColor: "rgba(212, 175, 55, 0.12)",
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  inRoutineBadgeText: {
    color: AUTH.gold,
    fontSize: 9,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.3,
  },
  tagGroup: {
    gap: 4,
  },
  tagGroupLabel: {
    color: AUTH.faint,
    fontSize: 9,
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: 0.35,
  },
  infoBtn: {
    width: 36,
    height: 36,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: AUTH.fieldBorder,
    backgroundColor: "rgba(10, 10, 12, 0.65)",
    alignItems: "center",
    justifyContent: "center",
  },
  infoBtnText: {
    color: AUTH.muted,
    fontSize: 14,
    fontWeight: "700",
  },
  statsHint: {
    color: AUTH.faint,
    fontSize: 11,
    fontStyle: "italic",
  },
  addLabel: {
    color: AUTH.gold,
    fontSize: 9,
    fontWeight: "700",
    marginTop: 2,
    textTransform: "uppercase",
  },
  addLabelDisabled: {
    color: AUTH.faint,
  },
  multiCheck: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: AUTH.fieldBorder,
    backgroundColor: "rgba(10, 10, 12, 0.8)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
  },
  multiCheckActive: {
    borderColor: WORKOUT_UI.borderGold,
    backgroundColor: WORKOUT_UI.chipBgActive,
  },
  multiCheckMark: {
    color: AUTH.gold,
    fontSize: 13,
    fontWeight: "700",
  },
  bottomBar: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    borderTopWidth: 1,
    borderTopColor: AUTH.cardBorder,
    backgroundColor: "rgba(10, 10, 12, 0.97)",
    paddingHorizontal: AUTH_PAD,
    paddingTop: 12,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  bottomBarBtn: {
    flex: 1,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: WORKOUT_UI.borderGold,
    backgroundColor: WORKOUT_UI.chipBgActive,
    paddingVertical: 14,
    alignItems: "center",
  },
  bottomBarBtnDisabled: {
    borderColor: AUTH.fieldBorder,
    backgroundColor: WORKOUT_UI.chipBg,
    opacity: 0.5,
  },
  bottomBarBtnText: {
    color: AUTH.gold,
    fontSize: 15,
    fontWeight: "700",
  },
  bottomBarClear: {
    paddingVertical: 10,
    paddingHorizontal: 8,
  },
  bottomBarClearText: {
    color: AUTH.muted,
    fontSize: 13,
    fontWeight: "600",
  },
  listHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 8,
    paddingHorizontal: 2,
  },
  listHeaderText: {
    color: AUTH.faint,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  listHeaderCount: {
    color: AUTH.muted,
    fontSize: 12,
    fontWeight: "600",
    fontVariant: ["tabular-nums"],
  },
  filterPanel: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(64, 64, 64, 0.55)",
    backgroundColor: "rgba(0, 0, 0, 0.35)",
    overflow: "hidden",
  },
  filterPanelHead: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 10,
    paddingHorizontal: 12,
    gap: 8,
  },
  filterPanelBody: {
    paddingHorizontal: 12,
    paddingBottom: 12,
    gap: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(64, 64, 64, 0.5)",
  },
  filterBadge: {
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    paddingHorizontal: 5,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(212, 175, 55, 0.2)",
  },
  filterBadgeText: {
    color: AUTH.gold,
    fontSize: 10,
    fontWeight: "700",
  },
  expandBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: AUTH.fieldBorder,
    backgroundColor: "rgba(10, 10, 12, 0.8)",
    alignItems: "center",
    justifyContent: "center",
  },
  expandIcon: {
    color: AUTH.muted,
    fontSize: 18,
    fontWeight: "300",
    lineHeight: 20,
  },
  expandIconOpen: {
    color: AUTH.gold,
  },
  rowCard: {
    flexDirection: "row",
    alignItems: "stretch",
    borderRadius: CATALOG_UI.cardRadius,
    borderWidth: 1,
    borderColor: "rgba(64, 64, 64, 0.45)",
    backgroundColor: "rgba(14, 14, 16, 0.92)",
    overflow: "hidden",
  },
  rowCardAdded: {
    borderColor: "rgba(212, 175, 55, 0.45)",
    backgroundColor: "rgba(20, 18, 12, 0.65)",
  },
  rowCardDisabled: {
    opacity: 0.55,
  },
  rowSwipeOuter: {
    marginBottom: CATALOG_UI.rowGap,
    overflow: "hidden",
    borderRadius: CATALOG_UI.cardRadius,
  },
  rowMain: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    paddingVertical: 10,
    paddingLeft: 10,
    paddingRight: 6,
    minWidth: 0,
  },
  rowTextCol: {
    flex: 1,
    minWidth: 0,
    gap: 6,
  },
  rowName: {
    color: AUTH.neutral100,
    fontSize: 16,
    fontWeight: "600",
    letterSpacing: -0.2,
  },
  rowDesc: {
    color: AUTH.muted,
    fontSize: 12,
    lineHeight: 16,
  },
  tagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 4,
  },
  tagMuscle: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(212, 175, 55, 0.28)",
    backgroundColor: "rgba(35, 32, 22, 0.65)",
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  tagMuscleText: {
    color: AUTH.gold,
    fontSize: 10,
    fontWeight: "600",
  },
  tagEquip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: "rgba(82, 82, 82, 0.8)",
    backgroundColor: "rgba(10, 10, 12, 0.7)",
    paddingHorizontal: 7,
    paddingVertical: 2,
  },
  tagEquipText: {
    color: AUTH.steel,
    fontSize: 10,
    fontWeight: "600",
  },
  chevron: {
    color: AUTH.faint,
    fontSize: 20,
    fontWeight: "300",
  },
  addCol: {
    width: 52,
    alignItems: "center",
    justifyContent: "center",
    borderLeftWidth: StyleSheet.hairlineWidth,
    borderLeftColor: "rgba(64, 64, 64, 0.5)",
    backgroundColor: "rgba(0, 0, 0, 0.2)",
  },
  addBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: WORKOUT_UI.borderGold,
    backgroundColor: WORKOUT_UI.chipBgActive,
    alignItems: "center",
    justifyContent: "center",
  },
  addBtnDisabled: {
    borderColor: AUTH.fieldBorder,
    backgroundColor: WORKOUT_UI.chipBg,
  },
  addIcon: {
    color: AUTH.gold,
    fontSize: 20,
    fontWeight: "700",
    marginTop: -1,
  },
  addIconDisabled: {
    color: AUTH.faint,
  },
  addedCheck: {
    color: AUTH.gold,
    fontSize: 16,
    fontWeight: "700",
  },
  emptyCard: {
    marginTop: 24,
    padding: 20,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: AUTH.fieldBorder,
    alignItems: "center",
  },
  emptyTitle: {
    color: AUTH.neutral100,
    fontSize: 15,
    fontWeight: "600",
    marginBottom: 6,
  },
  emptyBody: {
    color: AUTH.muted,
    fontSize: 13,
    textAlign: "center",
    lineHeight: 18,
  },
  embeddedPad: {
    paddingHorizontal: AUTH_PAD - 4,
  },
});
