import { Platform, StyleSheet } from "react-native";
import { AUTH, AUTH_PAD, authScreenStyles } from "./authUi";

/**
 * Estilos de entrenamientos alineados con auth, feed y perfil (AUTH + authScreenStyles).
 */
export const EXERCISE_BLOCK_PHOTO_SIZE = 56;

export const WORKOUT_UI = {
  bg: AUTH.bg,
  gold: AUTH.gold,
  surface: AUTH.bg,
  surfaceCard: AUTH.cardBg,
  surfaceRaised: AUTH.cardBg,
  border: AUTH.fieldBorder,
  borderSubtle: AUTH.cardBorder,
  borderGold: "rgba(212, 175, 55, 0.48)",
  borderGoldStrong: "rgba(212, 175, 55, 0.62)",
  goldGlow: "rgba(35, 32, 22, 0.96)",
  goldGlowActive: "rgba(48, 44, 28, 0.98)",
  accentLine: "rgba(212, 175, 55, 0.12)",
  footerBg: AUTH.cardBg,
  inputBg: AUTH.fieldBg,
  chipBg: "rgba(10, 10, 12, 0.6)",
  chipBgActive: "rgba(35, 32, 22, 0.96)",
  textOnGold: AUTH.gold,
} as const;

const cardShadow = Platform.select({
  ios: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.45,
    shadowRadius: 18,
  },
  android: { elevation: 8 },
  default: {},
});

export const workoutScreenStyles = StyleSheet.create({
  screenRoot: authScreenStyles.root,
  screenPad: {
    paddingHorizontal: AUTH_PAD,
  },
  cardGlowLine: authScreenStyles.cardGlowLine,
  sectionCard: {
    position: "relative",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: AUTH.cardBorder,
    backgroundColor: AUTH.cardBg,
    padding: 16,
    gap: 12,
    overflow: "hidden",
    ...cardShadow,
  },
  sectionCardAccent: {},
  sectionAccentBar: authScreenStyles.cardGlowLine,
  sectionTitle: authScreenStyles.cardTitle,
  sectionKicker: {
    color: AUTH.faint,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  fieldLabel: authScreenStyles.label,
  input: authScreenStyles.input,
  ghostBtn: {
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: AUTH.fieldBorder,
    backgroundColor: "rgba(10, 10, 12, 0.6)",
  },
  ghostBtnText: {
    color: AUTH.gold,
    fontSize: 13,
    fontWeight: "600",
  },
  outlineBtn: {
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: AUTH.fieldBorder,
    backgroundColor: "rgba(10, 10, 12, 0.6)",
  },
  outlineBtnText: {
    color: AUTH.steel,
    fontWeight: "600",
    fontSize: 14,
  },
  primaryFooterBtn: {
    ...authScreenStyles.cta,
    flex: 1,
    minHeight: 48,
  },
  primaryFooterBtnDisabled: authScreenStyles.ctaDisabled,
  primaryFooterBtnText: authScreenStyles.ctaLabel,
  secondaryFooterBtn: {
    minHeight: 48,
    paddingVertical: 13,
    paddingHorizontal: 14,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: AUTH.fieldBorder,
    backgroundColor: "rgba(10, 10, 12, 0.6)",
  },
  secondaryFooterBtnText: {
    color: AUTH.steel,
    fontSize: 15,
    fontWeight: "600",
  },
  stickyFooter: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    paddingHorizontal: AUTH_PAD,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(82, 82, 82, 0.65)",
    backgroundColor: AUTH.cardBg,
  },
  errorBanner: {
    color: AUTH.danger,
    fontSize: 14,
    fontWeight: "500",
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(248, 113, 113, 0.35)",
    backgroundColor: "rgba(40, 20, 20, 0.45)",
  },
  statPill: {
    flex: 1,
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 6,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: AUTH.fieldBorder,
    backgroundColor: "rgba(23, 23, 23, 0.5)",
    gap: 4,
  },
  statPillValue: {
    color: AUTH.neutral100,
    fontSize: 18,
    fontWeight: "700",
  },
  statPillValueAccent: {
    color: AUTH.gold,
    fontSize: 18,
    fontWeight: "700",
  },
  statPillLabel: {
    color: AUTH.faint,
    fontSize: 10,
    fontWeight: "600",
    textAlign: "center",
  },
  hubCard: {
    position: "relative",
    alignItems: "center",
    paddingVertical: 20,
    paddingHorizontal: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(212, 175, 55, 0.22)",
    backgroundColor: "rgba(23, 23, 23, 0.65)",
    gap: 10,
    overflow: "hidden",
  },
  hubIconRing: {
    width: 64,
    height: 64,
    borderRadius: 32,
    borderWidth: 1,
    borderColor: "rgba(212, 175, 55, 0.35)",
    backgroundColor: "rgba(35, 32, 22, 0.6)",
    alignItems: "center",
    justifyContent: "center",
  },
  hubTitle: {
    color: AUTH.neutral100,
    fontSize: 17,
    fontWeight: "700",
    textAlign: "center",
  },
  hubBody: authScreenStyles.cardSubtitle,
  listCard: {
    position: "relative",
    padding: 16,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: AUTH.cardBorder,
    backgroundColor: AUTH.cardBg,
    gap: 10,
    overflow: "hidden",
    ...cardShadow,
  },
  exerciseCard: {
    width: "100%",
    borderTopWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: AUTH.fieldBorder,
    backgroundColor: AUTH.cardBg,
    overflow: "hidden",
  },
  /** Lista a sangre en editor / entrenar (compensa padding del scroll). */
  exerciseBlocksList: {
    marginHorizontal: -AUTH_PAD,
    alignSelf: "stretch",
    gap: 0,
  },
  exerciseBlockCard: {
    position: "relative",
    width: "100%",
    alignSelf: "stretch",
    borderRadius: 0,
    borderLeftWidth: 0,
    borderRightWidth: 0,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: AUTH.fieldBorder,
    backgroundColor: AUTH.cardBg,
    overflow: "hidden",
  },
  exerciseBlockCardActive: {
    borderLeftWidth: 4,
    borderLeftColor: AUTH.gold,
    borderColor: "rgba(212, 175, 55, 0.48)",
    backgroundColor: "rgba(35, 32, 22, 0.52)",
    shadowColor: AUTH.gold,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 12,
    elevation: 6,
  },
  checkBtnBase: {
    minWidth: 44,
    minHeight: 44,
    width: 44,
    height: 44,
    borderRadius: 10,
    borderWidth: 1.5,
    alignItems: "center",
    justifyContent: "center",
  },
  exerciseBlockHeadRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 12,
    paddingHorizontal: 12,
    gap: 10,
  },
  exerciseBlockHeadMeta: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  exerciseBlockName: {
    color: AUTH.neutral100,
    fontSize: 15,
    fontWeight: "700",
  },
  exerciseBlockSubtitle: {
    color: AUTH.muted,
    fontSize: 11,
  },
  exerciseBlockCollapsedHint: {
    color: AUTH.faint,
    fontSize: 12,
  },
  exerciseBlockChevron: {
    color: AUTH.muted,
    fontSize: 11,
  },
  exerciseBlockBody: {
    paddingHorizontal: 12,
    paddingBottom: 14,
    gap: 10,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: "rgba(82, 82, 82, 0.5)",
  },
  exerciseBlockFieldLabel: {
    color: AUTH.faint,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  exerciseBlockIndexBadge: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: "rgba(10, 10, 12, 0.6)",
    borderWidth: 1,
    borderColor: AUTH.fieldBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  exerciseBlockIndexText: {
    color: AUTH.neutral100,
    fontWeight: "700",
    fontSize: 13,
  },
  exerciseBlockPhotoWrap: {
    position: "relative",
  },
  exerciseBlockIndexOnPhoto: {
    position: "absolute",
    right: -3,
    bottom: -3,
    minWidth: 18,
    height: 18,
    paddingHorizontal: 4,
    borderRadius: 9,
    backgroundColor: AUTH.cardBg,
    borderWidth: 1,
    borderColor: AUTH.fieldBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  exerciseBlockIndexOnPhotoDone: {
    borderColor: "rgba(212, 175, 55, 0.35)",
  },
  exerciseBlockIndexOnPhotoText: {
    color: AUTH.neutral100,
    fontSize: 10,
    fontWeight: "800",
  },
  exerciseBlockIconBtn: {
    width: 32,
    height: 32,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: AUTH.fieldBorder,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "rgba(10, 10, 12, 0.5)",
  },
  exerciseBlockIconBtnDanger: {
    borderColor: "rgba(248, 113, 113, 0.35)",
  },
  exerciseBlockIconBtnText: {
    color: AUTH.steel,
    fontSize: 15,
    fontWeight: "700",
  },
  exerciseBlockMoveRow: {
    flexDirection: "row",
    gap: 4,
    marginLeft: "auto",
  },
  exerciseBlockSetsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 4,
  },
  exerciseBlockSetActions: {
    flexDirection: "row",
    gap: 6,
  },
  exerciseBlockMiniBtn: {
    paddingVertical: 5,
    paddingHorizontal: 8,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: AUTH.fieldBorder,
    backgroundColor: "rgba(10, 10, 12, 0.6)",
  },
  exerciseBlockMiniBtnText: {
    color: AUTH.muted,
    fontSize: 11,
    fontWeight: "600",
  },
  exerciseBlockMiniBtnTextStrong: {
    color: AUTH.gold,
    fontSize: 11,
    fontWeight: "600",
  },
  exerciseBlockAddSetBtn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 7,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(212, 175, 55, 0.42)",
    backgroundColor: "rgba(35, 32, 22, 0.72)",
    minHeight: 36,
  },
  exerciseBlockAddSetBtnDisabled: {
    opacity: 0.38,
    borderColor: AUTH.fieldBorder,
    backgroundColor: "rgba(10, 10, 12, 0.5)",
  },
  exerciseBlockAddSetIcon: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: "rgba(212, 175, 55, 0.5)",
    backgroundColor: "rgba(48, 44, 28, 0.9)",
    alignItems: "center",
    justifyContent: "center",
  },
  exerciseBlockAddSetIconText: {
    color: AUTH.gold,
    fontSize: 16,
    fontWeight: "700",
    lineHeight: 18,
  },
  exerciseBlockAddSetLabel: {
    color: AUTH.gold,
    fontSize: 13,
    fontWeight: "700",
    letterSpacing: 0.2,
  },
  chip: {
    paddingVertical: 5,
    paddingHorizontal: 10,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: AUTH.fieldBorder,
    backgroundColor: "rgba(10, 10, 12, 0.6)",
  },
  chipActive: {
    borderColor: WORKOUT_UI.borderGold,
    backgroundColor: WORKOUT_UI.chipBgActive,
  },
  chipText: {
    color: AUTH.muted,
    fontSize: 11,
    fontWeight: "600",
  },
  chipTextActive: {
    color: AUTH.gold,
    fontWeight: "600",
  },
  tabBar: {
    flexDirection: "row",
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(82, 82, 82, 0.65)",
    backgroundColor: AUTH.bg,
  },
  tab: {
    flex: 1,
    alignItems: "center",
    paddingTop: 10,
    paddingBottom: 8,
    paddingHorizontal: 4,
  },
  tabSelected: {},
  tabText: {
    color: AUTH.muted,
    fontSize: 12,
    fontWeight: "600",
    textAlign: "center",
  },
  tabTextActive: {
    color: AUTH.gold,
    fontWeight: "600",
  },
  tabIndicator: {
    marginTop: 8,
    height: 2,
    width: "72%",
    maxWidth: 56,
    borderRadius: 1,
    backgroundColor: AUTH.gold,
  },
  tabIndicatorPlaceholder: {
    marginTop: 8,
    height: 2,
    width: "72%",
    maxWidth: 56,
  },
  indexBadge: {
    backgroundColor: "rgba(10, 10, 12, 0.6)",
    borderWidth: 1,
    borderColor: AUTH.fieldBorder,
    alignItems: "center",
    justifyContent: "center",
  },
  indexBadgeText: {
    color: AUTH.neutral100,
    fontWeight: "700",
  },
  progressTrack: {
    height: 3,
    borderRadius: 2,
    backgroundColor: "rgba(38, 38, 38, 0.9)",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: AUTH.gold,
    borderRadius: 2,
    opacity: 0.85,
  },
  setInputField: {
    minHeight: 44,
    borderWidth: 1,
    borderColor: AUTH.fieldBorder,
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 10,
    color: AUTH.neutral100,
    fontSize: 15,
    fontWeight: "600",
    backgroundColor: "rgba(10, 10, 12, 0.7)",
    textAlign: "center",
    fontVariant: ["tabular-nums"],
  },
  setInputFieldActive: {
    minHeight: 46,
    borderColor: "rgba(212, 175, 55, 0.55)",
    backgroundColor: "rgba(35, 32, 22, 0.55)",
  },
  setRowAlt: {
    backgroundColor: "rgba(255, 255, 255, 0.025)",
  },
  collapseIndicator: {
    width: 28,
    height: 28,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: AUTH.fieldBorder,
    backgroundColor: "rgba(10, 10, 12, 0.5)",
    alignItems: "center",
    justifyContent: "center",
  },
  collapseIndicatorText: {
    color: AUTH.muted,
    fontSize: 16,
    fontWeight: "300",
    lineHeight: 18,
  },
  linkText: authScreenStyles.linkText,
  pressed: authScreenStyles.linkPressed,
});
