import { StyleSheet } from "react-native";
import { AUTH } from "../../constants/authUi";

export const FEED_SUGGESTION_CARD_WIDTH = 92;
export const FEED_SUGGESTIONS_SECTION_INSET = 14;

export const feedSuggestionsStyles = StyleSheet.create({
  surface: {
    marginBottom: 10,
    paddingTop: 12,
    paddingBottom: 12,
    paddingHorizontal: 0,
  },
  surfaceInline: {
    marginBottom: 8,
    marginTop: 4,
    paddingTop: 12,
    paddingBottom: 12,
    paddingHorizontal: 0,
  },
  header: {
    flexDirection: "row",
    alignItems: "flex-start",
    justifyContent: "space-between",
    paddingHorizontal: FEED_SUGGESTIONS_SECTION_INSET,
    marginBottom: 10,
    gap: 10,
  },
  headerText: {
    flex: 1,
    minWidth: 0,
    gap: 3,
  },
  headerActions: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  title: {
    color: AUTH.neutral100,
    fontSize: 14,
    fontWeight: "700",
    letterSpacing: -0.2,
  },
  subtitle: {
    color: AUTH.muted,
    fontSize: 12,
    lineHeight: 16,
  },
  seeAllBtn: {
    paddingVertical: 6,
    paddingHorizontal: 8,
  },
  seeAllText: {
    color: AUTH.gold,
    fontSize: 12,
    fontWeight: "600",
  },
  dismissBtn: {
    width: 30,
    height: 30,
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "rgba(82, 82, 82, 0.65)",
    backgroundColor: "rgba(255, 255, 255, 0.03)",
  },
  dismissText: {
    color: AUTH.muted,
    fontSize: 18,
    lineHeight: 20,
    fontWeight: "400",
  },
  carousel: {
    flexDirection: "row",
    alignItems: "stretch",
    gap: 8,
    paddingHorizontal: FEED_SUGGESTIONS_SECTION_INSET,
  },
  carouselItem: {
    width: FEED_SUGGESTION_CARD_WIDTH,
  },
  listColumn: {
    paddingHorizontal: FEED_SUGGESTIONS_SECTION_INSET,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(212, 175, 55, 0.15)",
    backgroundColor: "rgba(14, 14, 16, 0.6)",
    overflow: "hidden",
  },
  listColumnEmbedded: {
    paddingHorizontal: 0,
    borderWidth: 0,
    backgroundColor: "transparent",
    borderRadius: 0,
  },
  listCardWrap: {
    alignSelf: "stretch",
  },
  listRowDivider: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: "rgba(64, 64, 64, 0.65)",
  },
  listRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    minHeight: 0,
  },
  listRowMain: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    minWidth: 0,
  },
  listAvatarWrap: {
    position: "relative",
  },
  listActiveDot: {
    position: "absolute",
    right: 0,
    bottom: 0,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#4ade80",
    borderWidth: 1.5,
    borderColor: "#0e0e10",
  },
  listMeta: {
    flex: 1,
    minWidth: 0,
    gap: 2,
  },
  listName: {
    color: AUTH.neutral100,
    fontSize: 14,
    fontWeight: "700",
  },
  listMetaLine: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    minWidth: 0,
  },
  listHint: {
    flex: 1,
    color: AUTH.muted,
    fontSize: 12,
    lineHeight: 16,
  },
  listFollowBtn: {
    alignSelf: "center",
    minWidth: 84,
    paddingVertical: 7,
    paddingHorizontal: 12,
    borderRadius: 18,
  },
  listFollowText: {
    fontSize: 12,
  },
  mutualRowStart: {
    justifyContent: "flex-start",
    marginBottom: 0,
  },
  cardFullWidth: {
    width: "100%",
    maxWidth: 420,
    alignSelf: "center",
  },
  card: {
    width: FEED_SUGGESTION_CARD_WIDTH,
    minHeight: 142,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(212, 175, 55, 0.2)",
    backgroundColor: "rgba(14, 14, 16, 0.95)",
    overflow: "hidden",
  },
  cardAccent: {
    height: 2,
    width: "100%",
    backgroundColor: "rgba(212, 175, 55, 0.55)",
  },
  cardBody: {
    flex: 1,
    justifyContent: "space-between",
    paddingTop: 8,
    paddingBottom: 8,
    paddingHorizontal: 8,
  },
  cardProfile: {
    flex: 1,
    width: "100%",
    alignItems: "center",
    justifyContent: "flex-start",
    minHeight: 0,
  },
  avatarRing: {
    padding: 2,
    borderRadius: 26,
    borderWidth: 1,
    borderColor: "rgba(212, 175, 55, 0.35)",
    backgroundColor: "rgba(212, 175, 55, 0.06)",
    marginBottom: 6,
  },
  activeDot: {
    position: "absolute",
    right: 2,
    bottom: 2,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#4ade80",
    borderWidth: 1.5,
    borderColor: "#0e0e10",
  },
  mutualRow: {
    flexDirection: "row",
    justifyContent: "center",
    gap: 2,
    marginBottom: 2,
  },
  mutualAvatarWrap: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "rgba(212, 175, 55, 0.35)",
    overflow: "hidden",
  },
  identity: {
    width: "100%",
    alignItems: "center",
    gap: 2,
    marginBottom: 6,
  },
  name: {
    color: AUTH.neutral100,
    fontSize: 11,
    fontWeight: "700",
    textAlign: "center",
    width: "100%",
  },
  hint: {
    color: AUTH.muted,
    fontSize: 9,
    lineHeight: 13,
    textAlign: "center",
    width: "100%",
  },
  followBtn: {
    alignSelf: "stretch",
    width: "100%",
    minWidth: 0,
    minHeight: 28,
    paddingVertical: 5,
    paddingHorizontal: 8,
    borderRadius: 14,
  },
  followText: {
    fontSize: 11,
  },
  pressed: {
    opacity: 0.88,
  },
  titleSkeleton: {
    width: 160,
    height: 14,
    borderRadius: 4,
    backgroundColor: "rgba(82, 82, 82, 0.35)",
  },
  subtitleSkeleton: {
    width: 120,
    height: 10,
    borderRadius: 4,
    backgroundColor: "rgba(82, 82, 82, 0.28)",
  },
});
