import { Platform, StyleSheet } from "react-native";
import { AUTH } from "../../../constants/authUi";
import { WORKOUT_UI, workoutScreenStyles } from "../../../constants/workoutScreenUi";

const cardShadow = Platform.select({
  ios: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
  },
  android: { elevation: 6 },
  default: {},
});

/** Estilos compartidos de la pantalla «Entreno completo» (marca Goi). */
export const sessionDetailStyles = StyleSheet.create({
  screenHeader: {
    flexDirection: "row",
    alignItems: "center",
  },
  backLink: {
    color: AUTH.gold,
    fontSize: 16,
    fontWeight: "600",
    width: 88,
  },
  screenTitle: {
    flex: 1,
    textAlign: "center",
    color: AUTH.neutral100,
    fontSize: 17,
    fontWeight: "700",
  },
  headerSpacer: { width: 88 },
  scroll: { gap: 14 },
  heroCard: {
    position: "relative",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: WORKOUT_UI.borderGold,
    backgroundColor: WORKOUT_UI.goldGlow,
    padding: 16,
    gap: 12,
    overflow: "hidden",
    ...cardShadow,
  },
  heroKicker: {
    ...workoutScreenStyles.sectionKicker,
    color: AUTH.gold,
    letterSpacing: 0.6,
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
  },
  titleIconRing: {
    width: 48,
    height: 48,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: WORKOUT_UI.borderGold,
    backgroundColor: "rgba(35, 32, 22, 0.85)",
    alignItems: "center",
    justifyContent: "center",
  },
  workoutTitle: {
    flex: 1,
    color: AUTH.neutral100,
    fontSize: 22,
    fontWeight: "800",
    lineHeight: 28,
    letterSpacing: -0.3,
  },
  authorRow: { flexDirection: "row", alignItems: "center", gap: 10 },
  authorName: { color: AUTH.neutral100, fontSize: 14, fontWeight: "700" },
  performedAt: { color: AUTH.faint, fontSize: 12 },
  durationRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    paddingVertical: 11,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: "rgba(212, 175, 55, 0.1)",
    borderWidth: 1,
    borderColor: WORKOUT_UI.borderGold,
  },
  durationLabel: {
    color: AUTH.faint,
    fontSize: 11,
    fontWeight: "700",
    letterSpacing: 0.4,
    textTransform: "uppercase",
  },
  durationValue: {
    color: AUTH.gold,
    fontSize: 18,
    fontWeight: "800",
  },
  quoteBox: {
    gap: 6,
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 10,
    backgroundColor: "rgba(10, 10, 12, 0.55)",
    borderLeftWidth: 3,
    borderLeftColor: AUTH.gold,
  },
  quoteLabel: {
    color: AUTH.gold,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.45,
    textTransform: "uppercase",
    opacity: 0.85,
  },
  quoteBody: {
    color: AUTH.muted,
    fontSize: 14,
    lineHeight: 20,
  },
  statsRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  sectionHead: { gap: 4, marginBottom: 2 },
  sectionKicker: workoutScreenStyles.sectionKicker,
  sectionTitle: {
    color: AUTH.neutral100,
    fontSize: 16,
    fontWeight: "700",
  },
  blocksList: { gap: 10 },
  exerciseCard: {
    position: "relative",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: AUTH.cardBorder,
    backgroundColor: AUTH.cardBg,
    padding: 14,
    gap: 12,
    overflow: "hidden",
    ...cardShadow,
  },
  exerciseHead: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  exerciseHeadMeta: {
    flex: 1,
    minWidth: 0,
    gap: 4,
    paddingTop: 4,
  },
  exerciseName: {
    color: AUTH.neutral100,
    fontSize: 17,
    fontWeight: "700",
    lineHeight: 22,
  },
  exerciseMeta: {
    color: AUTH.faint,
    fontSize: 12,
    fontWeight: "600",
  },
  setsList: { gap: 8 },
  setRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    alignItems: "flex-start",
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: "rgba(8, 8, 10, 0.75)",
    borderWidth: 1,
    borderColor: "rgba(212, 175, 55, 0.12)",
  },
  setRowPending: { opacity: 0.6, borderColor: AUTH.fieldBorder },
  setIndex: {
    width: 18,
    color: AUTH.gold,
    fontSize: 12,
    fontWeight: "800",
    marginTop: 14,
    opacity: 0.75,
  },
  setIndexPending: { color: AUTH.faint, opacity: 1 },
  typePill: {
    width: 32,
    height: 28,
    marginTop: 10,
    borderRadius: 7,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    backgroundColor: WORKOUT_UI.chipBg,
  },
  typePillMuted: { borderColor: AUTH.fieldBorder },
  metrics: {
    flex: 1,
    flexDirection: "row",
    gap: 8,
    minWidth: 0,
  },
  metricCell: {
    flex: 1,
    minWidth: 72,
    gap: 3,
    paddingVertical: 5,
    paddingHorizontal: 8,
    borderRadius: 8,
    backgroundColor: "rgba(18, 18, 22, 0.95)",
    borderWidth: 1,
    borderColor: "rgba(212, 175, 55, 0.14)",
  },
  metricLabel: {
    color: AUTH.faint,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.35,
    textTransform: "uppercase",
  },
  metricValue: {
    color: AUTH.gold,
    fontSize: 16,
    fontWeight: "800",
  },
  metricValueMuted: {
    color: AUTH.muted,
    fontWeight: "600",
  },
  metricEmpty: {
    color: AUTH.faint,
    fontWeight: "600",
    fontSize: 14,
  },
  metricPlan: {
    color: AUTH.faint,
    fontSize: 10,
    fontWeight: "500",
  },
  rpeCell: {
    minWidth: 44,
    gap: 3,
    paddingVertical: 5,
    paddingHorizontal: 8,
    borderRadius: 8,
    backgroundColor: "rgba(18, 18, 22, 0.95)",
    borderWidth: 1,
    borderColor: "rgba(212, 175, 55, 0.14)",
    alignItems: "center",
  },
  rpeValue: {
    color: AUTH.steel,
    fontSize: 15,
    fontWeight: "800",
  },
  extrasCol: {
    width: "100%",
    paddingLeft: 58,
    gap: 2,
  },
  extraLine: {
    color: AUTH.muted,
    fontSize: 11,
    fontWeight: "600",
  },
  notesCard: {
    ...workoutScreenStyles.sectionCard,
    gap: 8,
  },
  notesBody: {
    color: AUTH.muted,
    fontSize: 14,
    lineHeight: 21,
  },
  emptySets: {
    color: AUTH.faint,
    fontSize: 13,
    fontStyle: "italic",
  },
  quickSummary: {
    color: AUTH.muted,
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 18,
  },
  metaLine: {
    color: AUTH.faint,
    fontSize: 12,
    fontWeight: "500",
  },
  collapseBtn: {
    paddingVertical: 4,
    paddingHorizontal: 8,
    marginTop: 2,
  },
  collapseBtnText: {
    color: AUTH.gold,
    fontSize: 12,
    fontWeight: "700",
  },
  groupLabel: {
    color: AUTH.faint,
    fontSize: 10,
    fontWeight: "700",
    letterSpacing: 0.45,
    textTransform: "uppercase",
    marginTop: 4,
    marginBottom: 2,
    paddingLeft: 2,
  },
  highlightBadge: {
    alignSelf: "center",
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 6,
    borderWidth: 1,
    marginTop: 8,
  },
  highlightBadgePr: {
    backgroundColor: "rgba(212, 175, 55, 0.18)",
    borderColor: "rgba(212, 175, 55, 0.5)",
  },
  highlightBadgeTop: {
    backgroundColor: "rgba(115, 115, 115, 0.15)",
    borderColor: "rgba(115, 115, 115, 0.4)",
  },
  highlightBadgeText: {
    color: AUTH.gold,
    fontSize: 9,
    fontWeight: "800",
    letterSpacing: 0.4,
  },
  highlightBadgeTextTop: {
    color: AUTH.steel,
  },
  postLinkBtn: {
    alignSelf: "flex-start",
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: WORKOUT_UI.borderGold,
    backgroundColor: "rgba(212, 175, 55, 0.1)",
  },
  postLinkText: {
    color: AUTH.gold,
    fontSize: 13,
    fontWeight: "700",
  },
});
